server:
  port: 8083
spring:
  application:
    name: search-service
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  data:
    elasticsearch:
      cluster-name: elasticsearch
      cluster-nodes: 192.168.194.129:9300
  # 使多个@FeignClient注解可以使用相同服务名
  main:
    allow-bean-definition-overriding: true
  # 对象中为null的属性不返回给前端
  jackson:
    default-property-inclusion: non_null

